# -*- coding: utf-8 -*-
"""MilkCoffee.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QdOrl6O88KXtcPa6TVoXk-nMMM3sbWsT

Figure 1
"""

import matplotlib.pyplot as plt
import numpy as np

# Parameters
n_rounds = 50  # Number of rounds
x_0 = 0  # Start with no coffee in the milk jug

# r values
r_values = [0.1, 0.3, 0.5]

# Initialize the plot
plt.figure(figsize=(10, 6))

# Loop over the r values and plot the recurrence
for r in r_values:
    # Recalculate the recurrence for the current r
    x_values_r = [x_0]
    for n in range(1, n_rounds + 1):
        x_n = ((1 - r) * x_values_r[-1] + r) / (1 + r)
        x_values_r.append(x_n)

    # Plot the recurrence for the current r
    plt.plot(range(n_rounds + 1), x_values_r, label=f'r = {r}')

    # Add the horizontal dashed line at y = 0.5 (equilibrium)
plt.axhline(y=0.5, color='r', linestyle='--', label='Equilibrium (50%)')

# Label the plot
plt.title("Convergence of Coffee in Milk Jug for Different r Values", fontsize=22)
plt.xlabel("Rounds", fontsize=18)
plt.ylabel("Fraction of Coffee in Milk Jug", fontsize=18)
plt.legend(title="Transfer Fraction (r)", loc='lower right', fontsize=16, title_fontsize=16)
plt.savefig("coffee_recurrence.png")
plt.show()